rootProject.name = name

dependencyResolutionManagement {
	versionCatalogs {
		testLibs {
			from(files("gradle/test.libs.versions.toml"))
		}
		runtimeLibs {
			from(files("gradle/runtime.libs.versions.toml"))
		}
	}
}

// include ":lorenz-tiny"
// include ":stitch"

includeBuild("stitch") {
	dependencySubstitution {
		substitute(module("net.fabricmc:stitch"))
				.using(project(":"))
	}
}

includeBuild("lorenz-tiny") {
	dependencySubstitution {
		substitute(module("net.fabricmc:lorenz-tiny"))
				.using(project(":"))
	}
}
